name: Update M3U FAST

on:
  schedule:
    - cron: '*/30 * * * *'   # chạy mỗi 30 phút
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip & pycache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            __pycache__
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests==2.32.3 beautifulsoup4==4.12.3 curl-cffi==0.6.4

      - name: Run ccscraper.py
        run: python ccscraper.py

      - name: Commit & Push changes in private repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add chuoi_chien_streams.m3u chuoi_chien_streams.json
          git diff --cached --quiet || git commit -m "update m3u fast [skip ci]" --no-verify
          git push origin HEAD:main || (git commit --amend --no-edit && git push origin HEAD:main)

      - name: Sync tv.m3u to public repo
        run: |
          git clone https://x-access-token:${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/huybuonvp/xembongda.git
          cp chuoi_chien_streams.m3u xembongda/
          cd xembongda
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add chuoi_chien_streams.m3u
          git commit -m "Update chuoi_chien_streams.m3u from private repo" || echo "No changes"
          git push origin main
